name: Build Linux Tuncay Edition
on: [workflow_dispatch]
jobs:
  build-iso:
    runs-on: ubuntu-latest
    steps:
      - name: Install Live Build Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y live-build debootstrap

      - name: Setup Live Directory
        run: |
          mkdir tuncay_os && cd tuncay_os
          # Depoların hepsini (main universe restricted multiverse) açıyoruz:
          lb config --architecture amd64 --distribution noble --binary-images iso-hybrid \
            --mirror-bootstrap "http://archive.ubuntu.com/ubuntu/" \
            --mirror-binary "http://archive.ubuntu.com/ubuntu/" \
            --parent-mirror-bootstrap "http://archive.ubuntu.com/ubuntu/" \
            --parent-mirror-binary "http://archive.ubuntu.com/ubuntu/" \
            --components "main universe restricted multiverse"
          
          mkdir -p config/package-lists
          # Paketleri bulabilmesi için bu depolar şarttı
          echo "python3 python3-pip git xfce4 xfce4-goodies xorg" > config/package-lists/myos.list.chroot

      - name: Build ISO Image
        run: |
          cd tuncay_os
          sudo lb build

      - name: Upload Tuncay OS ISO
        uses: actions/upload-artifact@v4
        with:
          name: Tuncay-Edition-ISO
          path: tuncay_os/*.iso
